# Generated by Django 2.1 on 2018-09-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameproduct',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='gameproduct',
            unique_together={('name', 'shop')},
        ),
    ]
